configMapGenerator:
- files:
  - application.yml
  name: 82021988-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- newTag: "202410191203"
- name: ceappacr.azurecr.io/82021988
  newTag: "202410211217"
